apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: redis-slave-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-slave-1
  template:
    metadata:
      labels:
        app: redis-slave-1
    spec:
      containers:
        - name: redis-slave-1
          image: redis:6.0.6
          command: 
            - "redis-server"
          args:
            - "--slaveof"
            - "redis-master"
            - "6379"
          imagePullPolicy: Never
          resources:
            limits:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - name: redis-port
              containerPort: 6379
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave-1
spec:
  type: ClusterIP
  selector:
    app: redis-slave-1
  ports:
    - name: tcp
      port: 6379
      targetPort: 6379
