apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      containers:
        - name: redis-master
          image: redis:6.0.6
          imagePullPolicy: Never
          resources:
            limits:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - name: redis-port
              containerPort: 6379
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
spec:
  type: ClusterIP
  selector:
    app: redis-master
  ports:
    - name: tcp
      port: 6379
      targetPort: 6379
